import { Backpack, ExternalLink, FlaskConical, GitBranch, Languages, Route, ShieldAlert, Users } from 'lucide-react';
import { arcPresetSources } from '../arc-presets';
import { arcBenchmarkScenarios, sources } from '../data';
import { esperCycles } from '../esper-cycles';
import { useI18n } from '../i18n';
import { DataHealthPanel } from '../components/DataHealthPanel';
import { LocalizationEvidenceLegend } from '../components/LocalizationEvidenceNote';
import { TerminologyEvidenceTable } from '../components/TerminologyEvidenceTable';
import { Panel } from '../components/UI';
import { localizedSourceTitle } from '../gameTerms';
import { ascensionMaterials, ascensionSteps, characterAscensionProfiles, progressionDatasetSources } from '../progression-data';
import { rotationPresets } from '../rotation-presets';

export function MethodologyPage() {
  const { locale } = useI18n();
  const ru = locale === 'ru';
  const allSources = [...sources, ...arcPresetSources];

  return <div className="page calc-page methodology-page">
    <header className="page-heading"><div><span>{ru ? 'МЕТОДИКА' : 'METHODOLOGY'}</span><h1>{ru ? 'Формулы, ограничения и источники' : 'Formulas, assumptions and sources'}</h1><p>{ru ? 'Здесь можно проверить, откуда берутся цифры и названия, что именно учитывает сайт и где результат остаётся приблизительным.' : 'Review where numbers and names come from, what the site actually models and where results remain approximate.'}</p></div></header>

    <Panel className="terminology-note"><div className="panel-title"><Languages size={20} /><div><h2>{ru ? 'Как выбирается русское название' : 'How Russian terminology is selected'}</h2><p>{ru ? 'Один справочник не считается абсолютной истиной' : 'No single guide is treated as absolute truth'}</p></div></div><p>{ru ? 'Приоритет получают текст текущего русского клиента и официальные русские публикации. Затем используются актуальные выгрузки игровых данных и несколько независимых русскоязычных источников. Если варианты противоречат друг другу, основной термин не меняется автоматически: конфликт сохраняется в реестре и требует отдельной проверки.' : 'Current Russian client wording and official Russian publications have the highest priority, followed by current game-data transcriptions and multiple independent Russian references. Conflicting top-tier terms are never replaced automatically; the conflict is recorded for review.'}</p><p>{ru ? 'Английские идентификаторы персонажей, дуг и механик остаются неизменными в формулах, сохранениях и API. Русская подпись отвечает только за понятное отображение и поиск.' : 'Canonical English identifiers remain stable in formulas, saved state and APIs. Russian wording affects display and search only.'}</p></Panel>

    <LocalizationEvidenceLegend />
    <TerminologyEvidenceTable />
    <DataHealthPanel />

    <div className="method-grid">
      <Panel><div className="panel-title"><FlaskConical size={20} /><div><h2>{ru ? 'Базовая формула урона' : 'Baseline damage formula'}</h2><p>{ru ? 'Версия модели 0.2' : 'Model v0.2'}</p></div></div><pre>{ru ? 'Урон = итоговая АТК × множитель атаки × бонус урона × множитель ЗАЩ × сопротивление × средний критический множитель' : 'DMG = Total ATK × Attack Multiplier × DMG Bonus × DEF × RES × Expected CRIT'}</pre><p>{ru ? 'Итоговая АТК складывает базовую атаку персонажа и дуги, затем применяет процентные бонусы и дополнительную АТК числом. Множитель защиты зависит от уровней и снижения ЗАЩ. Сопротивление считается по публичной линейной модели, указанной в источниках ниже.' : 'Total ATK combines character and Arc base attack, then applies percentage bonuses and flat ATK. The defence multiplier uses character and enemy levels plus DEF reduction. Resistance follows the public linear model listed in the sources below.'}</p></Panel>
      <Panel><div className="panel-title"><Users size={20} /><div><h2>{ru ? 'Сравнение дуг по урону команды' : 'Team Arc comparison'}</h2><p>{ru ? 'Сортировка по полному урону' : 'Sorted by total damage'}</p></div></div><pre>{ru ? 'Урон команды = урон Ирой + базовый урон союзников × (1 + бонус союзникам × доля времени)' : 'Team DMG = Iroi DMG + Ally Base DMG × (1 + Ally Bonus × Uptime)'}</pre><p>{ru ? 'Постоянные характеристики и всегда активные эффекты учитываются полностью. Доля времени применяется только к эффектам с условием. Бонус союзникам не усиливает саму Ирой: он применяется только к заданному урону остальных членов команды.' : 'Substats and always-on effects apply fully. Uptime scales conditional effects only. Ally damage bonuses do not buff Iroi herself; they apply only to the configured damage from the rest of the team.'}</p></Panel>
      <Panel><div className="panel-title"><Route size={20} /><div><h2>{ru ? 'Как устроена Лаборатория ротаций' : 'How Rotation Lab data works'}</h2><p>{ru ? 'Порядок действий отделён от числовой симуляции' : 'Action order is separate from numeric simulation'}</p></div></div><p>{ru ? 'Каждая готовая ротация хранит ровно четырёх персонажей, последовательность фаз и шагов, ожидаемые циклы эспера, прямую ссылку на гайд, дату обновления гайда и дату проверки в проекте. Валидатор отклоняет неизвестных персонажей, повторяющиеся шаги и реакции, которые выбранный состав не способен запустить по своим типам эспера.' : 'Each preset stores exactly four characters, ordered phases and steps, expected Esper Cycles, a direct guide link, guide update date and project verification date. Validation rejects unknown characters, duplicate step IDs and cycles the selected Esper types cannot trigger.'}</p><p>{ru ? 'Ротация не преобразуется в DPS автоматически. Пока нет воспроизводимой временной шкалы анимаций, она остаётся тренировочной последовательностью. Перенос состава в калькулятор меняет только выбранных персонажей и сохраняет введённые пользователем числа.' : 'A rotation is not automatically converted into DPS. Without a reproducible animation timeline it remains a training sequence. Team transfer changes character identities only and preserves user-entered numeric values.'}</p></Panel>
      <Panel><div className="panel-title"><Backpack size={20} /><div><h2>{ru ? 'Как считается план прорыва' : 'How roster progression is calculated'}</h2><p>{ru ? `${characterAscensionProfiles.length} персонажей · ${ascensionSteps.length} этапов · ${Object.keys(ascensionMaterials).length} материалов` : `${characterAscensionProfiles.length} characters · ${ascensionSteps.length} steps · ${Object.keys(ascensionMaterials).length} materials`}</p></div></div><pre>{ru ? 'Нехватка материала = сумма неоплаченных этапов всех персонажей − общий инвентарь' : 'Material shortage = all unpaid character steps − shared inventory'}</pre><p>{ru ? 'Для каждого персонажа хранится число полностью оплаченных этапов прорыва. Расчёт берёт только последующие этапы, складывает одинаковые материалы между всеми персонажами и только после этого вычитает один общий инвентарь. Отрицательные значения заменяются нулём.' : 'Each character stores the number of fully paid breakthroughs. The engine takes only later steps, aggregates matching materials across the roster and then subtracts one shared inventory. Negative shortages are clamped to zero.'}</p><p>{ru ? 'Опыт персонажа, навыки, пассивные способности, жизненные навыки и дуги в эту сумму не входят. Поэтому результат показывает стоимость открытия предела 80 уровня, а не полную прокачку до максимума.' : 'Character EXP, abilities, passives, Life Skills and Arcs are excluded. The result is the cost to unlock the Lv. 80 cap, not a complete zero-to-MAX budget.'}</p></Panel>
      <Panel><div className="panel-title"><ShieldAlert size={20} /><div><h2>{ru ? 'Что пока не моделируется точно' : 'What is not yet simulated exactly'}</h2></div></div><ul><li>{ru ? 'Покадровое время анимаций, отмен действий и отдельных попаданий.' : 'Frame-level animation, cancel and hit timelines.'}</li><li>{ru ? 'Числовой вклад всех циклов эспера, разрушения и уникальных пассивных эффектов в общий DPS.' : 'The numeric DPS contribution of every Esper Cycle, Break event and character-specific passive.'}</li><li>{ru ? 'Полная стоимость опыта и прокачки способностей для всех персонажей.' : 'Complete roster-wide ability and character EXP costs.'}</li><li>{ru ? 'Скрытая внутренняя модель Rivyn Elowen.' : 'Rivyn Elowen’s private internal model.'}</li></ul></Panel>
    </div>

    <Panel className="benchmark-method-panel"><div className="panel-title"><GitBranch size={20} /><div><h2>{ru ? 'Почему готовые сравнения разделены' : 'Why benchmarks are separated'}</h2><p>{ru ? 'Результаты из разных таблиц нельзя складывать в один рейтинг' : 'Results from different tables are not mixed into one ranking.'}</p></div></div><p>{ru ? 'Публичная таблица Prydwen и расширенный скриншот Rivyn используют разные уровни смешивания и разные условия. Каждый сценарий отображается отдельно со своим источником и датой проверки. Режим пользовательских характеристик — третья независимая модель и не выдаётся за восстановление внутреннего калькулятора Rivyn.' : 'The public Prydwen table and the extended Rivyn screenshot use different Mixing Levels and assumptions. Each scenario is displayed separately with its own source and verification date. Custom stats are a third independent model and are not presented as a reconstruction of Rivyn’s calculator.'}</p><div className="benchmark-method-list">{arcBenchmarkScenarios.map((scenario) => <div key={scenario.id}><b>{scenario.title[locale]}</b><span>{allSources.find((source) => source.id === scenario.sourceId)?.publisher} · {scenario.verifiedAt}</span><p>{scenario.description[locale]}</p></div>)}</div></Panel>

    <h2 className="section-title">{ru ? 'Источники прорыва' : 'Progression sources'}</h2>
    <div className="source-list progression-method-sources">{progressionDatasetSources.map((source) => <Panel key={source.publisher}><div><b>{source.publisher}</b><span>{ru ? 'Обновлено' : 'Updated'}: {source.updatedAt}</span></div><p>{source.scope[locale]}</p><small>{ru ? 'Проверено' : 'Verified'}: {source.verifiedAt}</small><a href={source.url} target="_blank" rel="noreferrer">{ru ? 'Открыть источник' : 'Open'} <ExternalLink size={15} /></a></Panel>)}</div>

    <h2 className="section-title">{ru ? 'Источники ротаций и циклов эспера' : 'Rotation and Cycle sources'}</h2>
    <div className="source-list rotation-source-list">
      <Panel><div><b>{ru ? 'Циклы эспера: правила реакций' : 'Esper Cycles guide'}</b><span>{esperCycles[0]?.sourcePublisher}</span></div><p>{ru ? `Шесть парных и две тройные реакции. Все ${esperCycles.length} записей используют один актуальный справочник и отдельно проверяемые сочетания типов эспера.` : `Six pair and two triple reactions. All ${esperCycles.length} entries use the current guide and independently validated Esper-type combinations.`}</p><small>{ru ? 'Гайд обновлён' : 'Guide updated'}: {esperCycles[0]?.sourceUpdatedAt} · {ru ? 'Проверено' : 'Verified'}: {esperCycles[0]?.verifiedAt}</small><a href={esperCycles[0]?.sourceUrl} target="_blank" rel="noreferrer">{ru ? 'Открыть источник' : 'Open'} <ExternalLink size={15} /></a></Panel>
      {rotationPresets.map((preset) => <Panel key={preset.id}><div><b>{preset.title[locale]}</b><span>{preset.sourcePublisher}</span></div><p>{preset.description[locale]}</p><small>{ru ? 'Гайд обновлён' : 'Guide updated'}: {preset.sourceUpdatedAt} · {ru ? 'Проверено' : 'Verified'}: {preset.verifiedAt}</small><a href={preset.sourceUrl} target="_blank" rel="noreferrer">{ru ? 'Открыть источник' : 'Open'} <ExternalLink size={15} /></a></Panel>)}
    </div>

    <h2 className="section-title">{ru ? 'Реестр остальных источников' : 'Other source registry'}</h2><div className="source-list">{allSources.map((source) => <Panel key={source.id}><div><b>{localizedSourceTitle(source.title, locale)}</b>{ru ? <small className="original-name">{source.title}</small> : null}<span>{source.publisher}</span></div><p>{source.scope[locale]}</p><small>{ru ? 'Проверено' : 'Verified'}: {source.verifiedAt}</small>{source.url ? <a href={source.url} target="_blank" rel="noreferrer">{ru ? 'Открыть источник' : 'Open'} <ExternalLink size={15} /></a> : <span className="muted">{ru ? 'Локальный пользовательский источник' : 'Local user-provided source'}</span>}</Panel>)}</div>
  </div>;
}
