import { Backpack, ExternalLink, FlaskConical, GitBranch, Languages, Route, ShieldAlert, Users } from 'lucide-react';
import { arcPresetSources } from '../arc-presets';
import { arcBenchmarkScenarios, sources } from '../data';
import { esperCycles } from '../esper-cycles';
import { useI18n } from '../i18n';
import { Panel } from '../components/UI';
import { localizedSourceTitle } from '../gameTerms';
import { ascensionMaterials, ascensionSteps, characterAscensionProfiles, progressionDatasetSources } from '../progression-data';
import { rotationPresets } from '../rotation-presets';

export function MethodologyPage() {
  const { locale } = useI18n();
  const ru = locale === 'ru';
  const allSources = [...sources, ...arcPresetSources];

  return <div className="page calc-page">
    <header className="page-heading"><div><span>{ru ? 'МЕТОДИКА' : 'METHODOLOGY'}</span><h1>{ru ? 'Формулы, ограничения и источники' : 'Formulas, assumptions and sources'}</h1><p>{ru ? 'Здесь можно проверить, откуда берутся цифры, какие эффекты учитываются и где результат остаётся приблизительным.' : 'A public calculator should explain its numbers instead of asking users to trust a polished table.'}</p></div></header>

    <Panel className="terminology-note"><div className="panel-title"><Languages size={20} /><div><h2>{ru ? 'Русская терминология' : 'Russian terminology policy'}</h2><p>{ru ? 'В русской версии главным считается текст текущего русского клиента' : 'In-client Russian wording is primary'}</p></div></div><p>{ru ? 'Приоритет источников такой: текущий русский клиент → официальные русские публикации NTE → актуальные русскоязычные справочники. Когда варианты расходятся, используется написание из клиента или прямо подтверждённое владельцем проекта. Поэтому основное имя здесь — «Синку», а «Шинку» остаётся поисковым вариантом. Английское название показывается только второй строкой, чтобы предмет или персонажа можно было найти в международном гайде.' : 'Source priority is current Russian client wording, then official Russian NTE publications, then established current Russian guide usage. When the website and client disagree, the in-client term wins. Canonical English names remain secondary lookup references.'}</p><ul><li><b>{ru ? 'Синку' : 'Синку'}</b> — {ru ? 'основное имя персонажа; вариант «Шинку» распознаётся только при поиске.' : 'primary Shinku display name; Шинку is search-only.'}</li><li><b>{ru ? 'Оценщик' : 'Оценщик'}</b> — {ru ? 'основное обозначение главного персонажа; варианты «Зеро» и «Нулевой эспер» также находятся поиском.' : 'primary Zero display name; Зеро and Нулевой эспер remain searchable aliases.'}</li><li><b>{ru ? 'Чары' : 'Чары'}</b> — {ru ? 'название одного из шести атрибутов персонажа.' : 'Russian name of the Incantation attribute.'}</li><li><b>{ru ? 'Гибридный' : 'Гибридный'}</b> — {ru ? 'тип дуги Байканг, Фадии и других совместимых персонажей.' : 'Russian client-facing name for the Condensate/Synthesis Arc type.'}</li><li><b>{ru ? 'Цикл эспера' : 'Цикл эспера'}</b> — {ru ? 'система парных и тройных реакций атрибутов.' : 'Russian client term for the Esper Cycle reaction system.'}</li><li><b>{ru ? 'Сверхспособность' : 'Сверхспособность'}</b> — {ru ? 'особая атака, которая расходует накопленную энергию.' : 'Russian client term for Ultimate.'}</li><li><b>{ru ? 'Навык перенаправления' : 'Навык перенаправления'}</b> — {ru ? 'основной активный навык персонажа с собственной перезарядкой.' : 'Russian client term for Redirect Skill.'}</li><li><b>{ru ? 'Прорыв' : 'Прорыв'}</b> — {ru ? 'этап развития, который открывает следующие десять уровней персонажа или дуги.' : 'Russian client term for an ascension/breakthrough stage.'}</li><li><b>{ru ? 'Сломление' : 'Сломление'}</b> — {ru ? 'единая терминология проекта: шкала сломления, интенсивность сломления, сломленный враг и урон сломления.' : 'the consistent Break term used across the RU interface.'}</li><li><b>ATK · DEF · HP · CRIT · DPS · MAX · MIN</b> — {ru ? 'общепринятые сокращения, которые не переводятся.' : 'common abbreviations kept unchanged.'}</li></ul></Panel>

    <div className="method-grid">
      <Panel><div className="panel-title"><FlaskConical size={20} /><div><h2>{ru ? 'Базовая формула урона' : 'Baseline damage formula'}</h2><p>{ru ? 'Версия модели 0.2' : 'Model v0.2'}</p></div></div><pre>{ru ? 'Урон = итоговая ATK × множитель навыка × бонус урона × DEF × сопротивление × средний CRIT' : 'DMG = Total ATK × Skill Multiplier × DMG Bonus × DEF × RES × Expected CRIT'}</pre><p>{ru ? 'Итоговая ATK складывает базовую атаку персонажа и дуги, затем применяет постоянные и условные проценты ATK и дополнительную ATK числом. Множитель DEF зависит от уровней и снижения защиты. Сопротивление считается по линейной публичной модели NTE.wiki.' : 'Total ATK combines character and Arc base attack, then applies static ATK%, uptime-scaled conditional ATK% and flat ATK. DEF uses character/enemy levels and defence reduction. RES follows the linear resistance model documented by NTE.wiki.'}</p></Panel>
      <Panel><div className="panel-title"><Users size={20} /><div><h2>{ru ? 'Сравнение дуг по урону команды' : 'Team Arc comparison'}</h2><p>{ru ? 'Сортировка по полному урону' : 'Sorted by total damage'}</p></div></div><pre>{ru ? 'Урон команды = урон Ирой + базовый урон союзников × (1 + бонус союзникам × доля времени)' : 'Team DMG = Iroi DMG + Ally Base DMG × (1 + Ally Bonus × Uptime)'}</pre><p>{ru ? 'Постоянные характеристики и всегда активные пассивы учитываются полностью. Доля времени масштабирует только эффекты с условием. Бонус урона союзников не усиливает Ирой: он применяется только к заданному урону остальных членов команды.' : 'Substats and always-on passives apply fully and never depend on the uptime slider. Uptime scales explicitly conditional effects only. Ally damage bonuses do not buff the wearer; they apply only to the configured base damage from the rest of the team.'}</p></Panel>
      <Panel><div className="panel-title"><Route size={20} /><div><h2>{ru ? 'Как устроена Лаборатория ротаций' : 'How Rotation Lab data works'}</h2><p>{ru ? 'Порядок действий отделён от числовой симуляции' : 'Action order is separate from numeric simulation'}</p></div></div><p>{ru ? 'Каждая готовая ротация хранит ровно четырёх персонажей, последовательность фаз и шагов, ожидаемые циклы эсперов, прямую ссылку на гайд, дату обновления гайда и дату проверки в проекте. Валидатор отклоняет неизвестных персонажей, повторяющиеся шаги и реакции, которые выбранный состав не способен образовать по атрибутам.' : 'Each preset stores exactly four characters, ordered phases and steps, expected Esper Cycles, a direct guide link, guide update date and project verification date. Validation rejects unknown characters, duplicate step IDs and cycles the selected attributes cannot form.'}</p><p>{ru ? 'Ротация не преобразуется в DPS автоматически. Пока нет воспроизводимой точной временной шкалы анимаций, она остаётся тренировочным порядком действий. Перенос состава в калькулятор меняет только личности персонажей и сохраняет введённые пользователем числа.' : 'A rotation is not automatically converted into DPS. Without a reproducible animation timeline it remains a training sequence. Team transfer changes character identities only and preserves user-entered numeric values.'}</p></Panel>
      <Panel><div className="panel-title"><Backpack size={20} /><div><h2>{ru ? 'Как считается план прорыва' : 'How roster progression is calculated'}</h2><p>{ru ? `${characterAscensionProfiles.length} персонажей · ${ascensionSteps.length} этапов · ${Object.keys(ascensionMaterials).length} материалов` : `${characterAscensionProfiles.length} characters · ${ascensionSteps.length} steps · ${Object.keys(ascensionMaterials).length} materials`}</p></div></div><pre>{ru ? 'Остаток материала = сумма неоплаченных этапов всех персонажей − общий инвентарь' : 'Material shortage = all unpaid character steps − shared inventory'}</pre><p>{ru ? 'Для каждого персонажа хранится число полностью оплаченных этапов прорыва. Расчёт берёт только последующие этапы, складывает одинаковые материалы между всеми персонажами и лишь затем вычитает один общий инвентарь. Значения ниже нуля обрезаются до нуля.' : 'Each character stores the number of fully paid ascensions. The engine takes only later steps, aggregates matching materials across the full roster and then subtracts one shared inventory. Negative shortages are clamped to zero.'}</p><p>{ru ? 'EXP персонажа, навыки, пассивы, жизненные навыки и дуги не входят в эту сумму. Поэтому результат обозначает стоимость открытия предела ур. 80, а не полную прокачку до MAX.' : 'Character EXP, abilities, passives, Life Skills and Arcs are excluded. The result is the cost to unlock the Lv. 80 cap, not a complete zero-to-MAX budget.'}</p></Panel>
      <Panel><div className="panel-title"><ShieldAlert size={20} /><div><h2>{ru ? 'Что пока не моделируется точно' : 'What is not yet simulated exactly'}</h2></div></div><ul><li>{ru ? 'Покадровое время анимаций, отмен и попаданий.' : 'Frame-level animation, cancel and hit timelines.'}</li><li>{ru ? 'Числовой вклад всех циклов эсперов, сломления и уникальных пассивов в общий DPS.' : 'The numeric DPS contribution of every Esper Cycle, Break event and character-specific passive.'}</li><li>{ru ? 'Полная стоимость прокачки навыков и EXP для всех персонажей.' : 'Complete roster-wide ability and character EXP costs.'}</li><li>{ru ? 'Скрытая внутренняя модель Rivyn Elowen.' : 'Rivyn Elowen’s private internal model.'}</li></ul></Panel>
    </div>

    <Panel className="benchmark-method-panel"><div className="panel-title"><GitBranch size={20} /><div><h2>{ru ? 'Почему готовые сравнения разделены' : 'Why benchmarks are separated'}</h2><p>{ru ? 'Результаты из разных таблиц нельзя складывать в один рейтинг' : 'Results from different tables are not mixed into one ranking.'}</p></div></div><p>{ru ? 'Публичная таблица Prydwen и расширенный скриншот Rivyn используют разные уровни M и разные условия. Каждый сценарий отображается отдельно со своим источником и датой проверки. Режим пользовательских характеристик — третья независимая модель и не выдаётся за восстановление внутреннего калькулятора Rivyn.' : 'The public Prydwen table and the extended Rivyn screenshot use different Mixing Level sets and expose different detail. Each scenario is displayed separately with its own source, conditions and verification date. Custom stats are a third, independent partial model and are not presented as a reconstruction of Rivyn’s source calculator.'}</p><div className="benchmark-method-list">{arcBenchmarkScenarios.map((scenario) => <div key={scenario.id}><b>{scenario.title[locale]}</b><span>{allSources.find((source) => source.id === scenario.sourceId)?.publisher} · {scenario.verifiedAt}</span><p>{scenario.description[locale]}</p></div>)}</div></Panel>

    <h2 className="section-title">{ru ? 'Источники прорыва' : 'Progression sources'}</h2>
    <div className="source-list progression-method-sources">{progressionDatasetSources.map((source) => <Panel key={source.publisher}><div><b>{source.publisher}</b><span>{ru ? 'Обновлено' : 'Updated'}: {source.updatedAt}</span></div><p>{source.scope[locale]}</p><small>{ru ? 'Проверено' : 'Verified'}: {source.verifiedAt}</small><a href={source.url} target="_blank" rel="noreferrer">{ru ? 'Открыть источник' : 'Open'} <ExternalLink size={15} /></a></Panel>)}</div>

    <h2 className="section-title">{ru ? 'Источники ротаций и реакций' : 'Rotation and Cycle sources'}</h2>
    <div className="source-list rotation-source-list">
      <Panel><div><b>{ru ? 'Циклы эсперов: правила реакций' : 'Esper Cycles guide'}</b><span>{esperCycles[0]?.sourcePublisher}</span></div><p>{ru ? `Шесть парных и две тройные реакции. Все ${esperCycles.length} записей используют один актуальный справочник и отдельные проверяемые сочетания атрибутов.` : `Six pair and two triple reactions. All ${esperCycles.length} entries use the current guide and independently validated attribute combinations.`}</p><small>{ru ? 'Гайд обновлён' : 'Guide updated'}: {esperCycles[0]?.sourceUpdatedAt} · {ru ? 'Проверено' : 'Verified'}: {esperCycles[0]?.verifiedAt}</small><a href={esperCycles[0]?.sourceUrl} target="_blank" rel="noreferrer">{ru ? 'Открыть источник' : 'Open'} <ExternalLink size={15} /></a></Panel>
      {rotationPresets.map((preset) => <Panel key={preset.id}><div><b>{preset.title[locale]}</b><span>{preset.sourcePublisher}</span></div><p>{preset.description[locale]}</p><small>{ru ? 'Гайд обновлён' : 'Guide updated'}: {preset.sourceUpdatedAt} · {ru ? 'Проверено' : 'Verified'}: {preset.verifiedAt}</small><a href={preset.sourceUrl} target="_blank" rel="noreferrer">{ru ? 'Открыть источник' : 'Open'} <ExternalLink size={15} /></a></Panel>)}
    </div>

    <h2 className="section-title">{ru ? 'Реестр остальных источников' : 'Other source registry'}</h2><div className="source-list">{allSources.map((source) => <Panel key={source.id}><div><b>{localizedSourceTitle(source.title, locale)}</b>{ru ? <small className="original-name">{source.title}</small> : null}<span>{source.publisher}</span></div><p>{source.scope[locale]}</p><small>{ru ? 'Проверено' : 'Verified'}: {source.verifiedAt}</small>{source.url ? <a href={source.url} target="_blank" rel="noreferrer">{ru ? 'Открыть источник' : 'Open'} <ExternalLink size={15} /></a> : <span className="muted">{ru ? 'Локальный пользовательский источник' : 'Local user-provided source'}</span>}</Panel>)}</div>
  </div>;
}
