import { ExternalLink, FlaskConical, GitBranch, Languages, ShieldAlert, Users } from 'lucide-react';
import { arcPresetSources } from '../arc-presets';
import { arcBenchmarkScenarios, sources } from '../data';
import { useI18n } from '../i18n';
import { Panel } from '../components/UI';
import { localizedSourceTitle } from '../gameTerms';

export function MethodologyPage() {
  const { locale } = useI18n();
  const ru = locale === 'ru';
  const allSources = [...sources, ...arcPresetSources];

  return <div className="page calc-page">
    <header className="page-heading"><div><span>{ru ? 'МЕТОДИКА' : 'METHODOLOGY'}</span><h1>{ru ? 'Формулы, ограничения и источники' : 'Formulas, assumptions and sources'}</h1><p>{ru ? 'Здесь можно проверить, откуда берутся цифры, какие эффекты учитываются и где результат остаётся приблизительным.' : 'A public calculator should explain its numbers instead of asking users to trust a polished table.'}</p></div></header>

    <Panel className="terminology-note"><div className="panel-title"><Languages size={20} /><div><h2>{ru ? 'Как используются русские названия' : 'Russian terminology policy'}</h2><p>{ru ? 'Русский текст — основной в русской версии сайта' : 'Russian is primary in the RU interface'}</p></div></div><p>{ru ? 'У игры сейчас нет официального русского интерфейса, поэтому названия дуг, материалов и игровых терминов переведены для этого проекта на основе употребления в русскоязычном сообществе. Оригинальное английское название показывается мелким текстом там, где оно помогает найти предмет в глобальном клиенте. Общепринятые сокращения ATK, DEF, HP, CRIT, DPS, MAX и MIN не переводятся.' : 'The game currently has no official Russian interface. Russian game names are project/community translations, while canonical English names remain visible as secondary reference text. Common abbreviations such as ATK, DEF, HP, CRIT, DPS, MAX and MIN remain unchanged.'}</p></Panel>

    <div className="method-grid">
      <Panel><div className="panel-title"><FlaskConical size={20} /><div><h2>{ru ? 'Базовая формула урона' : 'Baseline damage formula'}</h2><p>{ru ? 'Версия модели 0.2' : 'Model v0.2'}</p></div></div><pre>{ru ? 'Урон = итоговая ATK × множитель навыка × бонус урона × DEF × сопротивление × средний CRIT' : 'DMG = Total ATK × Skill Multiplier × DMG Bonus × DEF × RES × Expected CRIT'}</pre><p>{ru ? 'Итоговая ATK складывает базовую атаку персонажа и дуги, затем применяет постоянные и условные проценты ATK и дополнительную ATK числом. Множитель DEF зависит от уровней и снижения защиты. Сопротивление считается по линейной публичной модели NTE.wiki.' : 'Total ATK combines character and Arc base attack, then applies static ATK%, uptime-scaled conditional ATK% and flat ATK. DEF uses character/enemy levels and defence reduction. RES follows the linear resistance model documented by NTE.wiki.'}</p></Panel>
      <Panel><div className="panel-title"><Users size={20} /><div><h2>{ru ? 'Сравнение дуг по урону команды' : 'Team Arc comparison'}</h2><p>{ru ? 'Сортировка по полному урону' : 'Sorted by total damage'}</p></div></div><pre>{ru ? 'Урон команды = урон Ирой + базовый урон союзников × (1 + бонус союзникам × доля времени)' : 'Team DMG = Iroi DMG + Ally Base DMG × (1 + Ally Bonus × Uptime)'}</pre><p>{ru ? 'Постоянные характеристики и всегда активные пассивы учитываются полностью. Доля времени масштабирует только эффекты с условием. Бонус урона союзников не усиливает Ирой: он применяется только к заданному урону остальных членов команды.' : 'Substats and always-on passives apply fully and never depend on the uptime slider. Uptime scales explicitly conditional effects only. Ally damage bonuses do not buff the wearer; they apply only to the configured base damage from the rest of the team.'}</p></Panel>
      <Panel><div className="panel-title"><ShieldAlert size={20} /><div><h2>{ru ? 'Что пока не моделируется точно' : 'What is not yet simulated exactly'}</h2></div></div><ul><li>{ru ? 'Покадровое время анимаций, отмен и попаданий.' : 'Frame-level animation, cancel and hit timelines.'}</li><li>{ru ? 'Все циклы эсперов, пробитие и уникальные пассивы персонажей.' : 'Every Esper Cycle, Break and character-specific passive.'}</li><li>{ru ? 'Скрытая внутренняя модель Rivyn Elowen.' : 'Rivyn Elowen’s private internal model.'}</li></ul></Panel>
    </div>

    <Panel className="benchmark-method-panel"><div className="panel-title"><GitBranch size={20} /><div><h2>{ru ? 'Почему готовые сравнения разделены' : 'Why benchmarks are separated'}</h2><p>{ru ? 'Результаты из разных таблиц нельзя складывать в один рейтинг' : 'Results from different tables are not mixed into one ranking.'}</p></div></div><p>{ru ? 'Публичная таблица Prydwen и расширенный скриншот Rivyn используют разные уровни M и разные условия. Каждый сценарий отображается отдельно со своим источником и датой проверки. Режим пользовательских характеристик — третья независимая модель и не выдаётся за восстановление внутреннего калькулятора Rivyn.' : 'The public Prydwen table and the extended Rivyn screenshot use different Mixing Level sets and expose different detail. Each scenario is displayed separately with its own source, conditions and verification date. Custom stats are a third, independent partial model and are not presented as a reconstruction of Rivyn’s source calculator.'}</p><div className="benchmark-method-list">{arcBenchmarkScenarios.map((scenario) => <div key={scenario.id}><b>{scenario.title[locale]}</b><span>{allSources.find((source) => source.id === scenario.sourceId)?.publisher} · {scenario.verifiedAt}</span><p>{scenario.description[locale]}</p></div>)}</div></Panel>

    <h2 className="section-title">{ru ? 'Реестр источников' : 'Source registry'}</h2><div className="source-list">{allSources.map((source) => <Panel key={source.id}><div><b>{localizedSourceTitle(source.title, locale)}</b>{ru ? <small className="original-name">{source.title}</small> : null}<span>{source.publisher}</span></div><p>{source.scope[locale]}</p><small>{ru ? 'Проверено' : 'Verified'}: {source.verifiedAt}</small>{source.url ? <a href={source.url} target="_blank" rel="noreferrer">{ru ? 'Открыть источник' : 'Open'} <ExternalLink size={15} /></a> : <span className="muted">{ru ? 'Локальный пользовательский источник' : 'Local user-provided source'}</span>}</Panel>)}</div>
  </div>;
}
