import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import { I18nProvider } from './i18n';
import './styles.css';
import './arc-scenarios.css';
import './arc-state.css';
import './arc-recommendations.css';
import './arc-experience.css';
import './resilient-images.css';
import './guided-ux.css';
import './database.css';
import './character-catalog.css';
import './team-input.css';
import './team-readiness.css';
import './home-tools.css';
import './rotation-lab.css';
import './rotation-catalog.css';
import './rotation-practice.css';
import './progression-roster.css';
import './progression-next.css';
import './progression-automation.css';
import './localization-evidence.css';
import './terminology-audit.css';
import './data-health.css';
import './interface-foundation.css';
import './imageFallbackRuntime';

createRoot(document.getElementById('root')!).render(<StrictMode><I18nProvider><App /></I18nProvider></StrictMode>);
