import type { VerifiedVisibleAction } from './verified-visible-actions';

const verifiedAt = '2026-08-05';
const icy = (character: string) => `https://www.icy-veins.com/neverness-to-everness/${character}-profile-skills`;

/**
 * Batch C keeps current English source titles where Russian-client wording is
 * not confirmed. Every record is one exact level-10 action or one explicitly
 * scoped trigger. Duration, cooldown and possible repeat counts are never
 * converted into a rotation total.
 */
export const verifiedVisibleActionsBatchC: readonly VerifiedVisibleAction[] = [
  {
    id: 'haniel.genesse-technique.full-combo.level-10',
    characterName: 'Haniel',
    title: { ru: 'Genesse Technique · полная последовательность', en: 'Genesse Technique: full sequence' },
    description: {
      ru: 'Все пять опубликованных ступеней базовой атаки: 83,8% + 22,4% × 2 + 116,3% + 31,2% × 4 + 105,5% = 475,2% АТК. Английское имя сохранено до подтверждения русского клиента.',
      en: 'All five published Basic Attack stages: 83.8% + 22.4% × 2 + 116.3% + 31.2% × 4 + 105.5% = 475.2% ATK.',
    },
    multiplier: 83.8 + 22.4 * 2 + 116.3 + 31.2 * 4 + 105.5,
    requiredSkill: 'basic',
    requiredLevel: 10,
    assumedConditions: [{
      ru: 'Все удары пятиступенчатой последовательности попали по одной цели; заряженный, воздушный и ответный варианты не включены.',
      en: 'Every hit of the five-stage sequence connects with one target; charged, aerial and Critical Riposte variants are excluded.',
    }],
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('haniel'),
    sourceUpdatedAt: '2026-07-07',
    verifiedAt,
  },
  {
    id: 'haniel.silent-moonlit-forest-guardian.direct.level-10',
    characterName: 'Haniel',
    title: { ru: 'Silent Moonlit Forest Guardian · прямой удар', en: 'Silent Moonlit Forest Guardian: direct hit' },
    description: {
      ru: 'Прямой урон одного применения навыка: 199,9% АТК × 2 = 399,8% АТК. Последующие Ensemble и Symphony сюда не входят.',
      en: 'One Skill cast direct damage: 199.9% ATK × 2 = 399.8% ATK. Later Ensemble and Symphony triggers are excluded.',
    },
    multiplier: 199.9 * 2,
    requiredSkill: 'skill',
    requiredLevel: 10,
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('haniel'),
    sourceUpdatedAt: '2026-07-07',
    verifiedAt,
  },
  {
    id: 'haniel.a-melody-named-haniel.initial.level-10',
    characterName: 'Haniel',
    title: { ru: 'A Melody Named Haniel · начальный удар', en: 'A Melody Named Haniel: initial hit' },
    description: {
      ru: 'Опубликованный прямой урон одного применения сверхспособности: 599,7% АТК. Десятисекундное состояние, Ensemble — Symphony и дополнительный удар активного персонажа не повторяются автоматически.',
      en: 'Published direct damage for one Ultimate cast: 599.7% ATK. The ten-second state, Ensemble — Symphony and active-character follow-up are not repeated automatically.',
    },
    multiplier: 599.7,
    requiredSkill: 'ultimate',
    requiredLevel: 10,
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('haniel'),
    sourceUpdatedAt: '2026-07-07',
    verifiedAt,
  },
  {
    id: 'haniel.easter-egg-time.level-10',
    characterName: 'Haniel',
    title: { ru: 'Easter Egg Time · одно применение', en: 'Easter Egg Time: one cast' },
    description: {
      ru: 'Один опубликованный удар навыка поддержки: 399,8% АТК.',
      en: 'One published Support Skill hit: 399.8% ATK.',
    },
    multiplier: 399.8,
    requiredSkill: 'support',
    requiredLevel: 10,
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('haniel'),
    sourceUpdatedAt: '2026-07-07',
    verifiedAt,
  },

  {
    id: 'sakiri.devour-whole.press.level-10',
    characterName: 'Sakiri',
    title: { ru: 'Devour Whole · нажатие', en: 'Devour Whole: press' },
    description: {
      ru: 'Вариант Burp при нажатии: 335,4% + 464,2% = 799,6% АТК. Урон пробуждения A2 по массе цели не добавляется.',
      en: 'Burp press version: 335.4% + 464.2% = 799.6% ATK. Awakening 2 mass-scaling damage is excluded.',
    },
    multiplier: 335.4 + 464.2,
    requiredSkill: 'skill',
    requiredLevel: 10,
    assumedConditions: [{ ru: 'Учитывается вариант навыка при нажатии.', en: 'The press version of the Skill is used.' }],
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('sakiri'),
    sourceUpdatedAt: '2026-07-07',
    verifiedAt,
  },
  {
    id: 'sakiri.devour-whole.hold.level-10',
    characterName: 'Sakiri',
    title: { ru: 'Devour Whole · удержание', en: 'Devour Whole: hold' },
    description: {
      ru: 'Вариант Gravity Eater при удержании: 180,5% + 237,5% + 381,6% = 799,6% АТК.',
      en: 'Gravity Eater hold version: 180.5% + 237.5% + 381.6% = 799.6% ATK.',
    },
    multiplier: 180.5 + 237.5 + 381.6,
    requiredSkill: 'skill',
    requiredLevel: 10,
    assumedConditions: [{ ru: 'Учитывается вариант навыка при удержании.', en: 'The held version of the Skill is used.' }],
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('sakiri'),
    sourceUpdatedAt: '2026-07-07',
    verifiedAt,
  },
  {
    id: 'sakiri.feast-of-gluttony.level-10',
    characterName: 'Sakiri',
    title: { ru: 'Feast of Gluttony · одно применение', en: 'Feast of Gluttony: one cast' },
    description: {
      ru: 'Шесть опубликованных попаданий сверхспособности: 239,9% АТК × 5 + 599,7% АТК = 1799,2% АТК. Командный бонус Атаки моделируется отдельным временным эффектом.',
      en: 'Six published Ultimate hits: 239.9% ATK × 5 + 599.7% ATK = 1799.2% ATK. The team ATK bonus is modeled as a separate timed effect.',
    },
    multiplier: 239.9 * 5 + 599.7,
    requiredSkill: 'ultimate',
    requiredLevel: 10,
    assumedConditions: [{
      ru: 'Все шесть попаданий Gravity Slurry попали по проверяемой цели; A3 и другие условные бонусы не применены.',
      en: 'All six Gravity Slurry hits connect with the tested target; A3 and other conditional bonuses are excluded.',
    }],
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('sakiri'),
    sourceUpdatedAt: '2026-07-07',
    verifiedAt,
  },
  {
    id: 'sakiri.squash.level-10',
    characterName: 'Sakiri',
    title: { ru: 'Squash! · одно применение', en: 'Squash!: one cast' },
    description: {
      ru: 'Один опубликованный удар навыка поддержки: 399,8% АТК.',
      en: 'One published Support Skill hit: 399.8% ATK.',
    },
    multiplier: 399.8,
    requiredSkill: 'support',
    requiredLevel: 10,
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('sakiri'),
    sourceUpdatedAt: '2026-07-07',
    verifiedAt,
  },

  {
    id: 'baicang.heart-of-heaven-and-earth.level-10',
    characterName: 'Baicang',
    title: { ru: 'Heart of Heaven and Earth · один удар', en: 'Heart of Heaven and Earth: one hit' },
    description: {
      ru: 'Один опубликованный удар базового варианта навыка: 239,9% АТК.',
      en: 'One published hit of the base Skill version: 239.9% ATK.',
    },
    multiplier: 239.9,
    requiredSkill: 'skill',
    requiredLevel: 10,
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('baicang'),
    sourceUpdatedAt: '2026-06-08',
    verifiedAt,
  },
  {
    id: 'baicang.silenced-thought.full-composition.level-10',
    characterName: 'Baicang',
    title: { ru: 'Silenced Thought · полная композиция', en: 'Silenced Thought: full composition' },
    description: {
      ru: 'Три ракеты и опубликованный взрыв: 199,9% АТК × 3 + 239,9% АТК = 839,6% АТК.',
      en: 'Three missiles plus the published explosion: 199.9% ATK × 3 + 239.9% ATK = 839.6% ATK.',
    },
    multiplier: 199.9 * 3 + 239.9,
    requiredSkill: 'skill',
    requiredLevel: 10,
    assumedConditions: [{
      ru: 'Все три ракеты и взрыв попали по одной цели после уклонения.',
      en: 'All three missiles and the explosion connect with one target after a dodge.',
    }],
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('baicang'),
    sourceUpdatedAt: '2026-06-08',
    verifiedAt,
  },
  {
    id: 'baicang.such-crime.level-10',
    characterName: 'Baicang',
    title: { ru: 'Such Crime · одно применение', en: 'Such Crime: one cast' },
    description: {
      ru: 'Опубликованный урон варианта навыка после Formless Words или Unrestrained Words: 559,7% АТК.',
      en: 'Published Skill-version damage after Formless Words or Unrestrained Words: 559.7% ATK.',
    },
    multiplier: 559.7,
    requiredSkill: 'skill',
    requiredLevel: 10,
    assumedConditions: [{
      ru: 'Предварительно сработал Formless Words или Unrestrained Words.',
      en: 'Formless Words or Unrestrained Words was triggered first.',
    }],
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('baicang'),
    sourceUpdatedAt: '2026-06-08',
    verifiedAt,
  },
  {
    id: 'baicang.judgment-of-autumn.expansion.level-10',
    characterName: 'Baicang',
    title: { ru: 'Judgment of Autumn · раскрытие области', en: 'Judgment of Autumn: domain expansion' },
    description: {
      ru: 'Начальный опубликованный урон раскрытия области: 799,6% АТК. Периодический урон и последующие Power Word не включены.',
      en: 'Published initial domain-expansion damage: 799.6% ATK. Damage over time and later Power Word triggers are excluded.',
    },
    multiplier: 799.6,
    requiredSkill: 'ultimate',
    requiredLevel: 10,
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('baicang'),
    sourceUpdatedAt: '2026-06-08',
    verifiedAt,
  },
  {
    id: 'baicang.judgment-of-autumn.one-dot-tick.level-10',
    characterName: 'Baicang',
    title: { ru: 'Judgment of Autumn · один DoT-тик', en: 'Judgment of Autumn: one DoT tick' },
    description: {
      ru: 'Один опубликованный тик периодического урона: 80% АТК. Сайт намеренно не выводит общее число тиков из длительности 12 секунд и интервала 2 секунды.',
      en: 'One published damage-over-time tick: 80% ATK. The site deliberately does not infer a total tick count from the 12-second duration and two-second interval.',
    },
    multiplier: 80,
    requiredSkill: 'ultimate',
    requiredLevel: 10,
    assumedConditions: [{ ru: 'Учитывается ровно одно срабатывание DoT.', en: 'Exactly one DoT trigger is counted.' }],
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('baicang'),
    sourceUpdatedAt: '2026-06-08',
    verifiedAt,
  },
  {
    id: 'baicang.judgment-of-autumn.silence-trigger.level-10',
    characterName: 'Baicang',
    title: { ru: 'Judgment of Autumn · одно Silence', en: 'Judgment of Autumn: one Silence trigger' },
    description: {
      ru: 'Одно опубликованное срабатывание Silence внутри области: 599,7% АТК. A1 и повторные Power Word не добавляются.',
      en: 'One published Silence trigger inside the domain: 599.7% ATK. A1 and repeated Power Words are excluded.',
    },
    multiplier: 599.7,
    requiredSkill: 'ultimate',
    requiredLevel: 10,
    assumedConditions: [{ ru: 'В области сработало ровно одно Power Word Silence.', en: 'Exactly one Power Word Silence triggers inside the domain.' }],
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('baicang'),
    sourceUpdatedAt: '2026-06-08',
    verifiedAt,
  },
  {
    id: 'baicang.judgment-of-autumn.objurgate-trigger.level-10',
    characterName: 'Baicang',
    title: { ru: 'Judgment of Autumn · одно Objurgate', en: 'Judgment of Autumn: one Objurgate trigger' },
    description: {
      ru: 'Одно опубликованное срабатывание Objurgate внутри области: 399,8% АТК.',
      en: 'One published Objurgate trigger inside the domain: 399.8% ATK.',
    },
    multiplier: 399.8,
    requiredSkill: 'ultimate',
    requiredLevel: 10,
    assumedConditions: [{ ru: 'В области сработало ровно одно Power Word Objurgate.', en: 'Exactly one Power Word Objurgate triggers inside the domain.' }],
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('baicang'),
    sourceUpdatedAt: '2026-06-08',
    verifiedAt,
  },
  {
    id: 'baicang.judgment-of-autumn.bless-trigger.level-10',
    characterName: 'Baicang',
    title: { ru: 'Judgment of Autumn · одно Bless', en: 'Judgment of Autumn: one Bless trigger' },
    description: {
      ru: 'Опубликованная композиция одного Bless: взрыв 60% АТК + две ракеты по 30% АТК = 120% АТК. Восстановление ОЗ не входит в формулу урона.',
      en: 'Published composition of one Bless: 60% ATK explosion + two 30% ATK missiles = 120% ATK. HP restoration is outside the damage formula.',
    },
    multiplier: 60 + 30 * 2,
    requiredSkill: 'ultimate',
    requiredLevel: 10,
    assumedConditions: [{
      ru: 'Один Power Word Bless сработал, и обе ракеты попали по проверяемой цели.',
      en: 'One Power Word Bless triggers and both missiles connect with the tested target.',
    }],
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('baicang'),
    sourceUpdatedAt: '2026-06-08',
    verifiedAt,
  },

  {
    id: 'daffodill.still-waters.full-sequence.level-10',
    characterName: 'Daffodill',
    title: { ru: 'Still Waters · полная обычная последовательность', en: 'Still Waters: full normal sequence' },
    description: {
      ru: 'Опубликованная обычная последовательность: 81,8% АТК × 2 + 67,4% АТК × 5 + 99,6% АТК = 600,2% АТК.',
      en: 'Published normal sequence: 81.8% ATK × 2 + 67.4% ATK × 5 + 99.6% ATK = 600.2% ATK.',
    },
    multiplier: 81.8 * 2 + 67.4 * 5 + 99.6,
    requiredSkill: 'basic',
    requiredLevel: 10,
    assumedConditions: [{
      ru: 'Все опубликованные удары обычной последовательности попали по одной цели.',
      en: 'Every published hit of the normal sequence connects with one target.',
    }],
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('daffodill'),
    sourceUpdatedAt: '2026-07-07',
    verifiedAt,
  },
  {
    id: 'daffodill.echoes.enhanced-sequence.level-10',
    characterName: 'Daffodill',
    title: { ru: 'Echoes · усиленная последовательность', en: 'Echoes: enhanced sequence' },
    description: {
      ru: 'Опубликованная усиленная последовательность перенаправляемого навыка: 69,6% АТК × 6 + 182,1% АТК = 599,7% АТК.',
      en: 'Published enhanced Redirect Skill sequence: 69.6% ATK × 6 + 182.1% ATK = 599.7% ATK.',
    },
    multiplier: 69.6 * 6 + 182.1,
    requiredSkill: 'skill',
    requiredLevel: 10,
    assumedConditions: [{
      ru: 'Resonance достиг максимума и действие заменено на Echoes; все попадания соединены.',
      en: 'Resonance reached its maximum and the action was replaced by Echoes; every hit connects.',
    }],
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('daffodill'),
    sourceUpdatedAt: '2026-07-07',
    verifiedAt,
  },
  {
    id: 'daffodill.finale.initial-composition.level-10',
    characterName: 'Daffodill',
    title: { ru: 'Finale · начальная композиция', en: 'Finale: initial composition' },
    description: {
      ru: 'Опубликованный прямой урон применения: 98,6% × 3 + 50,6% × 3 + 102,1% × 7 + 436,4% = 1598,7% АТК. Phantom Step и последующие парирования не включены.',
      en: 'Published direct cast damage: 98.6% × 3 + 50.6% × 3 + 102.1% × 7 + 436.4% = 1598.7% ATK. Phantom Step and later parries are excluded.',
    },
    multiplier: 98.6 * 3 + 50.6 * 3 + 102.1 * 7 + 436.4,
    requiredSkill: 'ultimate',
    requiredLevel: 10,
    assumedConditions: [{
      ru: 'Все опубликованные части начального урона попали по проверяемой цели; бонус +10% и другие условные усиления не подмешаны.',
      en: 'Every published part of the initial cast connects; the +10% increase and other conditional modifiers are excluded.',
    }],
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('daffodill'),
    sourceUpdatedAt: '2026-07-07',
    verifiedAt,
  },
  {
    id: 'daffodill.finale.one-parry-extra.level-10',
    characterName: 'Daffodill',
    title: { ru: 'Finale · одно дополнительное парирование', en: 'Finale: one Parry Attack extra hit' },
    description: {
      ru: 'Один опубликованный дополнительный удар успешного Parry Attack: 599,7% АТК. Сайт не повторяет его по числу доступных Phantom Step.',
      en: 'One published successful Parry Attack extra hit: 599.7% ATK. The site does not repeat it by the number of available Phantom Step charges.',
    },
    multiplier: 599.7,
    requiredSkill: 'ultimate',
    requiredLevel: 10,
    assumedConditions: [{
      ru: 'Во время Insight успешно выполнено ровно одно парирование; пассивный бонус Phantom Step +80% не применяется автоматически.',
      en: 'Exactly one parry succeeds during Insight; the Phantom Step +80% passive bonus is not applied automatically.',
    }],
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('daffodill'),
    sourceUpdatedAt: '2026-07-07',
    verifiedAt,
  },
  {
    id: 'daffodill.crossed-blades.level-10',
    characterName: 'Daffodill',
    title: { ru: 'Crossed Blades · одно применение', en: 'Crossed Blades: one cast' },
    description: {
      ru: 'Один опубликованный удар навыка поддержки: 399,8% АТК.',
      en: 'One published Support Skill hit: 399.8% ATK.',
    },
    multiplier: 399.8,
    requiredSkill: 'support',
    requiredLevel: 10,
    sourcePublisher: 'Icy Veins',
    sourceUrl: icy('daffodill'),
    sourceUpdatedAt: '2026-07-07',
    verifiedAt,
  },
];
