import type { VerifiedVisibleAction } from './verified-visible-actions';

const verifiedAt = '2026-08-05';
const icy = (character: string) => `https://www.icy-veins.com/neverness-to-everness/${character}-profile-skills`;

/**
 * Batch E completes the current final-ATK action pass. Duration-dependent
 * repeats, recorded ally attacks, healing and Base-ATK lamb ratios remain
 * excluded rather than being converted into final-ATK damage.
 */
export const verifiedVisibleActionsBatchE: readonly VerifiedVisibleAction[] = [
  {
    id: 'hotori.misty-moon-style.full-sequence.level-10',
    characterName: 'Hotori',
    title: { ru: 'Misty Moon Style · полная последовательность', en: 'Misty Moon Style: full sequence' },
    description: {
      ru: 'Все пять опубликованных ступеней: 40% + (70,6% + 8,8% × 2 + 144,3%) + 22,6% × 5 + (28,4% × 2 + 133,1%) + (48,6% + 90,2%) = 714,2% АТК.',
      en: 'All five published stages: 40% + (70.6% + 8.8% × 2 + 144.3%) + 22.6% × 5 + (28.4% × 2 + 133.1%) + (48.6% + 90.2%) = 714.2% ATK.',
    },
    multiplier: 40 + (70.6 + 8.8 * 2 + 144.3) + 22.6 * 5 + (28.4 * 2 + 133.1) + (48.6 + 90.2),
    requiredSkill: 'basic',
    requiredLevel: 10,
    assumedConditions: [{ ru: 'Все попадания пяти ступеней пришлись по проверяемой цели.', en: 'Every hit of all five stages connects with the tested target.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('hotori'), sourceUpdatedAt: '2026-07-31', verifiedAt,
  },
  {
    id: 'hotori.rippling-waves.level-10',
    characterName: 'Hotori',
    title: { ru: 'Rippling Waves · одно удержание', en: 'Rippling Waves: one hold attack' },
    description: { ru: 'Четыре опубликованных попадания удерживаемой базовой атаки: 48% АТК × 4 = 192% АТК.', en: 'Four published held Basic Attack hits: 48% ATK × 4 = 192% ATK.' },
    multiplier: 48 * 4,
    requiredSkill: 'basic', requiredLevel: 10,
    assumedConditions: [{ ru: 'Все четыре попадания достигли цели.', en: 'All four hits connect.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('hotori'), sourceUpdatedAt: '2026-07-31', verifiedAt,
  },
  {
    id: 'hotori.present-replay.direct.level-10',
    characterName: 'Hotori',
    title: { ru: 'Present Replay · прямой урон', en: 'Present Replay: direct damage' },
    description: { ru: 'Семь прямых попаданий навыка: 80% АТК × 6 + 120,1% АТК = 600,1% АТК. Записанные атаки союзников не включены.', en: 'Seven direct Skill hits: 80% ATK × 6 + 120.1% ATK = 600.1% ATK. Recorded ally attacks are excluded.' },
    multiplier: 80 * 6 + 120.1,
    requiredSkill: 'skill', requiredLevel: 10,
    assumedConditions: [{ ru: 'Все семь прямых попаданий Present Replay достигли цели.', en: 'All seven direct Present Replay hits connect.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('hotori'), sourceUpdatedAt: '2026-07-31', verifiedAt,
  },
  {
    id: 'hotori.worlds-tide.initial-composition.level-10',
    characterName: 'Hotori',
    title: { ru: 'World’s Tide · начальная композиция', en: 'World’s Tide: initial composition' },
    description: { ru: 'Десять начальных попаданий сверхспособности: 34% × 6 + 260,5% + 88,6% + 522,9% × 2 = 1598,9% АТК. Катана, финишер и повторы союзников считаются отдельно.', en: 'Ten initial Ultimate hits: 34% × 6 + 260.5% + 88.6% + 522.9% × 2 = 1598.9% ATK. Katana attacks, Finisher and ally replays are separate.' },
    multiplier: 34 * 6 + 260.5 + 88.6 + 522.9 * 2,
    requiredSkill: 'ultimate', requiredLevel: 10,
    assumedConditions: [{ ru: 'Все десять начальных попаданий достигли цели.', en: 'All ten initial hits connect.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('hotori'), sourceUpdatedAt: '2026-07-31', verifiedAt,
  },
  {
    id: 'hotori.worlds-tide.katana-full-sequence.level-10',
    characterName: 'Hotori',
    title: { ru: 'World’s Tide · полная серия катаны', en: 'World’s Tide: full katana sequence' },
    description: { ru: 'Все пять опубликованных ступеней катаны: 76,2% + (46,8% + 127,3%) + (18,4% × 3 + 89%) + (51% + 59,4% + 50,8% + 84,8%) + (17% + 442%) = 1099,5% АТК.', en: 'All five published katana stages total 1099.5% ATK.' },
    multiplier: 76.2 + (46.8 + 127.3) + (18.4 * 3 + 89) + (51 + 59.4 + 50.8 + 84.8) + (17 + 442),
    requiredSkill: 'ultimate', requiredLevel: 10,
    assumedConditions: [{ ru: 'Выполнены все пять ступеней катаны; финишер не включён.', en: 'All five katana stages are completed; the Finisher is excluded.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('hotori'), sourceUpdatedAt: '2026-07-31', verifiedAt,
  },
  {
    id: 'hotori.worlds-tide.finisher.level-10',
    characterName: 'Hotori',
    title: { ru: 'World’s Tide · один финишер', en: 'World’s Tide: one Finisher' },
    description: { ru: 'Один опубликованный финишер после 10 комбо: 599,7% АТК. Пассивное увеличение коэффициента не применяется автоматически.', en: 'One published Finisher after 10 combo stacks: 599.7% ATK. Passive ratio increases are not applied automatically.' },
    multiplier: 599.7,
    requiredSkill: 'ultimate', requiredLevel: 10,
    assumedConditions: [{ ru: 'Набрано 10 комбо и финишер сработал ровно один раз.', en: 'Ten combo stacks were reached and the Finisher triggered exactly once.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('hotori'), sourceUpdatedAt: '2026-07-31', verifiedAt,
  },
  {
    id: 'hotori.shopkeepers-authority.level-10',
    characterName: 'Hotori',
    title: { ru: 'Shopkeeper’s Authority · одно применение', en: 'Shopkeeper’s Authority: one cast' },
    description: { ru: 'Один опубликованный удар навыка поддержки: 399,8% АТК.', en: 'One published Support Skill hit: 399.8% ATK.' },
    multiplier: 399.8,
    requiredSkill: 'support', requiredLevel: 10,
    sourcePublisher: 'Icy Veins', sourceUrl: icy('hotori'), sourceUpdatedAt: '2026-07-31', verifiedAt,
  },

  {
    id: 'iroi.collaboration.full-sequence.level-10',
    characterName: 'Iroi',
    title: { ru: 'Collaboration · полная последовательность', en: 'Collaboration: full sequence' },
    description: { ru: 'Все пять ступеней: 151,9% + 31,8% × 3 + 20,6% × 8 + 140,3% + 51,6% × 3 = 707,2% АТК.', en: 'All five stages: 151.9% + 31.8% × 3 + 20.6% × 8 + 140.3% + 51.6% × 3 = 707.2% ATK.' },
    multiplier: 151.9 + 31.8 * 3 + 20.6 * 8 + 140.3 + 51.6 * 3,
    requiredSkill: 'basic', requiredLevel: 10,
    assumedConditions: [{ ru: 'Все попадания пяти ступеней достигли цели.', en: 'Every hit of all five stages connects.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('iroi'), sourceUpdatedAt: '2026-07-27', verifiedAt,
  },
  {
    id: 'iroi.daydream.full-charge.level-10',
    characterName: 'Iroi',
    title: { ru: 'Daydream · полный заряд', en: 'Daydream: full charge' },
    description: { ru: 'Три опубликованные части полного заряда: 73,6% × 3 + 176,7% + 79,6% = 477,1% АТК.', en: 'Three published full-charge parts: 73.6% × 3 + 176.7% + 79.6% = 477.1% ATK.' },
    multiplier: 73.6 * 3 + 176.7 + 79.6,
    requiredSkill: 'basic', requiredLevel: 10,
    assumedConditions: [{ ru: 'Daydream заряжен до третьей ступени, и все опубликованные части попали.', en: 'Daydream is charged to stage three and all published parts connect.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('iroi'), sourceUpdatedAt: '2026-07-27', verifiedAt,
  },
  {
    id: 'iroi.lucid-dream.full-burst.level-10',
    characterName: 'Iroi',
    title: { ru: 'Lucid Dream · полная очередь', en: 'Lucid Dream: full burst' },
    description: { ru: 'Тридцать пять опубликованных попаданий: 47,4% АТК × 35 = 1659% АТК.', en: 'Thirty-five published hits: 47.4% ATK × 35 = 1659% ATK.' },
    multiplier: 47.4 * 35,
    requiredSkill: 'basic', requiredLevel: 10,
    assumedConditions: [{ ru: 'Полная очередь из 35 попаданий достигла цели.', en: 'The complete 35-hit burst connects.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('iroi'), sourceUpdatedAt: '2026-07-27', verifiedAt,
  },
  {
    id: 'iroi.future-self-continuity.direct.level-10',
    characterName: 'Iroi',
    title: { ru: 'Future Self Continuity · прямой урон', en: 'Future Self Continuity: direct damage' },
    description: { ru: 'Прямые атаки трёх ягнят: 299,9% + 35,8% × 7 + 249,9% = 800,4% АТК. Лечение, усиление от базовой Атаки и Regression-атаки не включены.', en: 'Direct three-lamb attacks: 299.9% + 35.8% × 7 + 249.9% = 800.4% ATK. Healing, Base-ATK buffing and Regression attacks are excluded.' },
    multiplier: 299.9 + 35.8 * 7 + 249.9,
    requiredSkill: 'skill', requiredLevel: 10,
    assumedConditions: [{ ru: 'Все части прямой атаки трёх ягнят достигли цели.', en: 'Every direct part of the three-lamb attack connects.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('iroi'), sourceUpdatedAt: '2026-07-27', verifiedAt,
  },
  {
    id: 'iroi.3-8-billion-year-mirage.post-cast.level-10',
    characterName: 'Iroi',
    title: { ru: '3.8-Billion-Year Mirage · начальный урон', en: '3.8-Billion-Year Mirage: post-cast damage' },
    description: { ru: 'Один опубликованный начальный удар: 599,7% АТК. Периодический урон и лечение считаются отдельно.', en: 'One published post-cast hit: 599.7% ATK. Damage over time and healing are separate.' },
    multiplier: 599.7,
    requiredSkill: 'ultimate', requiredLevel: 10,
    sourcePublisher: 'Icy Veins', sourceUrl: icy('iroi'), sourceUpdatedAt: '2026-07-27', verifiedAt,
  },
  {
    id: 'iroi.3-8-billion-year-mirage.one-dot-tick.level-10',
    characterName: 'Iroi',
    title: { ru: '3.8-Billion-Year Mirage · один тик', en: '3.8-Billion-Year Mirage: one DoT tick' },
    description: { ru: 'Ровно один опубликованный тик периодического урона: 50% АТК. Число тиков не выводится из расхода Imagination.', en: 'Exactly one published damage-over-time tick: 50% ATK. Tick count is not inferred from Imagination consumption.' },
    multiplier: 50,
    requiredSkill: 'ultimate', requiredLevel: 10,
    assumedConditions: [{ ru: 'Учитывается ровно один тик Dream of the Ivory Gate.', en: 'Exactly one Dream of the Ivory Gate tick is counted.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('iroi'), sourceUpdatedAt: '2026-07-27', verifiedAt,
  },
  {
    id: 'iroi.bang.level-10',
    characterName: 'Iroi',
    title: { ru: 'Bang! · одно применение', en: 'Bang!: one cast' },
    description: { ru: 'Один опубликованный удар навыка поддержки: 399,8% АТК. Лечение не включено.', en: 'One published Support Skill hit: 399.8% ATK. Healing is excluded.' },
    multiplier: 399.8,
    requiredSkill: 'support', requiredLevel: 10,
    sourcePublisher: 'Icy Veins', sourceUrl: icy('iroi'), sourceUpdatedAt: '2026-07-27', verifiedAt,
  },
  {
    id: 'iroi.strategy-tit-for-tat.awakening-two',
    characterName: 'Iroi',
    title: { ru: 'Пробуждение 2 · одна помощь', en: 'Awakening 2: one assist' },
    description: { ru: 'Одна явно описанная помощь случайного ягнёнка: 200% АТК. Лечение и автоматические повторы по откату не включены.', en: 'One explicitly described random-lamb assist: 200% ATK. Healing and automatic cooldown repeats are excluded.' },
    multiplier: 200,
    requiredSkill: 'support', requiredLevel: '—', minimumAwakening: 2,
    assumedConditions: [{ ru: 'Союзник применил навык, и помощь сработала один раз; внутренний откат — 5 секунд.', en: 'An ally cast a skill and the assist triggered once; internal cooldown is five seconds.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('iroi'), sourceUpdatedAt: '2026-07-27', verifiedAt,
  },

  {
    id: 'mint.perfect-containment.full-sequence.level-10',
    characterName: 'Mint',
    title: { ru: 'Perfect Containment · полная последовательность', en: 'Perfect Containment: full sequence' },
    description: { ru: 'Все пять ступеней: (20,8% + 46,2%) + 34% + (52,4% + 68,2%) + 36,8% + (51% + 104,5%) = 413,9% АТК.', en: 'All five stages total 413.9% ATK.' },
    multiplier: 20.8 + 46.2 + 34 + 52.4 + 68.2 + 36.8 + 51 + 104.5,
    requiredSkill: 'basic', requiredLevel: 10,
    assumedConditions: [{ ru: 'Все попадания пяти ступеней достигли цели.', en: 'Every hit of all five stages connects.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('mint'), sourceUpdatedAt: '2026-07-28', verifiedAt,
  },
  {
    id: 'mint.super-claws.level-10',
    characterName: 'Mint',
    title: { ru: 'Super Claws · одно применение', en: 'Super Claws: one cast' },
    description: { ru: 'Два опубликованных попадания навыка: 179,9% АТК × 2 = 359,8% АТК.', en: 'Two published Skill hits: 179.9% ATK × 2 = 359.8% ATK.' },
    multiplier: 179.9 * 2,
    requiredSkill: 'skill', requiredLevel: 10,
    assumedConditions: [{ ru: 'Оба прохода достигли цели.', en: 'Both passes connect.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('mint'), sourceUpdatedAt: '2026-07-28', verifiedAt,
  },
  {
    id: 'mint.thunderous-whirlwind-slash.full-composition.level-10',
    characterName: 'Mint',
    title: { ru: 'Thunderous Whirlwind Slash · полная композиция', en: 'Thunderous Whirlwind Slash: full composition' },
    description: { ru: 'Начальный удар, пять ударов когтями и финальный разрез: 265,1% + 117,5% × 5 + 746,6% = 1599,2% АТК.', en: 'Impact, five claw hits and final slash: 265.1% + 117.5% × 5 + 746.6% = 1599.2% ATK.' },
    multiplier: 265.1 + 117.5 * 5 + 746.6,
    requiredSkill: 'ultimate', requiredLevel: 10,
    assumedConditions: [{ ru: 'Все семь опубликованных частей достигли цели.', en: 'All seven published parts connect.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('mint'), sourceUpdatedAt: '2026-07-28', verifiedAt,
  },
  {
    id: 'mint.invincible-tornado-slash.level-10',
    characterName: 'Mint',
    title: { ru: 'Invincible Tornado Slash · одно применение', en: 'Invincible Tornado Slash: one cast' },
    description: { ru: 'Один опубликованный удар навыка поддержки: 399,8% АТК.', en: 'One published Support Skill hit: 399.8% ATK.' },
    multiplier: 399.8,
    requiredSkill: 'support', requiredLevel: 10,
    sourcePublisher: 'Icy Veins', sourceUrl: icy('mint'), sourceUpdatedAt: '2026-07-28', verifiedAt,
  },

  {
    id: 'skia.arresting-art.full-sequence.level-10',
    characterName: 'Skia',
    title: { ru: 'Arresting Art · полная последовательность', en: 'Arresting Art: full sequence' },
    description: { ru: 'Все пять ступеней: 60,8% + (7,4% × 2 + 37,8%) + (64,2% + 91,8%) + 78,2% + (58,8% + 110,7%) = 517,1% АТК. Fang Thrust считается отдельно.', en: 'All five stages total 517.1% ATK. Fang Thrust is separate.' },
    multiplier: 60.8 + (7.4 * 2 + 37.8) + (64.2 + 91.8) + 78.2 + (58.8 + 110.7),
    requiredSkill: 'basic', requiredLevel: 10,
    assumedConditions: [{ ru: 'Все попадания основной серии достигли цели; Fang Thrust не включён.', en: 'Every main-chain hit connects; Fang Thrust is excluded.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('skia'), sourceUpdatedAt: '2026-07-28', verifiedAt,
  },
  {
    id: 'skia.fang-thrust.one-basic-trigger.level-10',
    characterName: 'Skia',
    title: { ru: 'Fang Thrust · одно базовое срабатывание', en: 'Fang Thrust: one Basic trigger' },
    description: { ru: 'Ровно одно базовое срабатывание Fang Thrust: 20% АТК. Количество целей и повторов не выводится автоматически.', en: 'Exactly one base Fang Thrust trigger: 20% ATK. Target and repeat counts are not inferred.' },
    multiplier: 20,
    requiredSkill: 'basic', requiredLevel: 10,
    assumedConditions: [{ ru: 'Учитывается ровно один Fang Thrust.', en: 'Exactly one Fang Thrust is counted.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('skia'), sourceUpdatedAt: '2026-07-28', verifiedAt,
  },
  {
    id: 'skia.shadow-hound-chase.initial-composition.level-10',
    characterName: 'Skia',
    title: { ru: 'Shadow Hound Chase · начальная композиция', en: 'Shadow Hound Chase: initial composition' },
    description: { ru: 'Четыре удара и нырок: 60% × 4 + 9,2% + 50,8% = 300% АТК. Последующие касания Fang Thrust и выход из режима считаются отдельно.', en: 'Four strikes and dive: 60% × 4 + 9.2% + 50.8% = 300% ATK. Later Fang Thrust collisions and the outro are separate.' },
    multiplier: 60 * 4 + 9.2 + 50.8,
    requiredSkill: 'skill', requiredLevel: 10,
    assumedConditions: [{ ru: 'Все шесть начальных частей достигли цели.', en: 'All six initial parts connect.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('skia'), sourceUpdatedAt: '2026-07-28', verifiedAt,
  },
  {
    id: 'skia.shadow-hound-chase.one-fang-extra.level-10',
    characterName: 'Skia',
    title: { ru: 'Shadow Hound Chase · одно доп. срабатывание Fang Thrust', en: 'Shadow Hound Chase: one Fang Thrust extra trigger' },
    description: { ru: 'Ровно одно дополнительное срабатывание Fang Thrust в режиме: 109,9% АТК. Интервал 0,35 с не превращается в автоматическое число повторов.', en: 'Exactly one Fang Thrust extra trigger in the mode: 109.9% ATK. The 0.35-second interval is not converted into an automatic repeat count.' },
    multiplier: 109.9,
    requiredSkill: 'skill', requiredLevel: 10,
    assumedConditions: [{ ru: 'Учитывается ровно одно дополнительное срабатывание.', en: 'Exactly one extra trigger is counted.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('skia'), sourceUpdatedAt: '2026-07-28', verifiedAt,
  },
  {
    id: 'skia.shadow-hound-gnaw.outro.level-10',
    characterName: 'Skia',
    title: { ru: 'Shadow Hound Gnaw · один выход', en: 'Shadow Hound Gnaw: one outro' },
    description: { ru: 'Один опубликованный удар при выходе из режима: 100% АТК.', en: 'One published mode-outro hit: 100% ATK.' },
    multiplier: 100,
    requiredSkill: 'skill', requiredLevel: 10,
    assumedConditions: [{ ru: 'Режим завершился с одним ударом выхода.', en: 'The mode ended with one outro hit.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('skia'), sourceUpdatedAt: '2026-07-28', verifiedAt,
  },
  {
    id: 'skia.the-pack.full-composition.level-10',
    characterName: 'Skia',
    title: { ru: 'The Pack · полная композиция', en: 'The Pack: full composition' },
    description: { ru: 'Расширение тени и три схождения: 580,1% + 139,7% × 3 = 999,2% АТК. Последующее усиление Fang Thrust не включено.', en: 'Shadow spread and three converging hits: 580.1% + 139.7% × 3 = 999.2% ATK. The later Fang Thrust buff is excluded.' },
    multiplier: 580.1 + 139.7 * 3,
    requiredSkill: 'ultimate', requiredLevel: 10,
    assumedConditions: [{ ru: 'Все четыре части сверхспособности достигли цели.', en: 'All four Ultimate parts connect.' }],
    sourcePublisher: 'Icy Veins', sourceUrl: icy('skia'), sourceUpdatedAt: '2026-07-28', verifiedAt,
  },
  {
    id: 'skia.arrest-warrant.level-10',
    characterName: 'Skia',
    title: { ru: 'Arrest Warrant · одно применение', en: 'Arrest Warrant: one cast' },
    description: { ru: 'Один опубликованный удар навыка поддержки: 399,8% АТК.', en: 'One published Support Skill hit: 399.8% ATK.' },
    multiplier: 399.8,
    requiredSkill: 'support', requiredLevel: 10,
    sourcePublisher: 'Icy Veins', sourceUrl: icy('skia'), sourceUpdatedAt: '2026-07-28', verifiedAt,
  },
];
